on:
  push:
  pull_request:
    branches:
      — main
      — develop

jobs:
  # The “build” workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
          go version
          go install github.com/mgechev/revive@latest
          go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Run build & package
        run: |
          ./bundle.sh
          go build -v -x .
          go build -v -x --race .
          fyne package -os linux

      # Enable proper linting once docs added
      - name: Run vet & revive
        run: |
          go vet -x .
          revive -config revive.toml -formatter stylish ./...

#      - name: Run testing
#        run: cd test && go test -v